export default {
  PATH: '@module/new',
  actions: {
    UPDATE_USER_SELECTED_REVIEW: '@actions/updateUserSelectedReview',
    UPDATE_USER_SELECTED_REDS: '@actions/updateUserSelectedReds',
    UPDATE_SECTOR_SELECTED_REVIEW: '@actions/updateSectorSelectedReview',
    UPDATE_SECTOR_SELECTED_REDS: '@actions/updateSectorSelectedReds',
    LIST_NEWS: '@actions/listNews',
    LIST_NEWS_REDS: '@actions/listNewsReds',
    GET_NEW: '@actions/getNew',
    GET_NEW_BY_PHONE: '@actions/getNewByPhone',
    SAVE_NEW: '@actions/saveNew',
    UPDATE_NEW: '@actions/updateNew',
    COMPLETE_DATA_NEW: '@actions/completeDataNew',
    UPDATE_STATUS_NEW: '@actions/updateStatusNew',
    DELETE_NEW: '@actions/deleteNew',
  },
  getters: {
  },
  mutations: {
    SET_USER_SELECTED_REVIEW: '@mutations/setUserSelectedReview',
    SET_USER_SELECTED_REDS: '@mutations/setUserSelectedReds',
    SET_SECTOR_SELECTED_REVIEW: '@mutations/setSectorSelectedReview',
    SET_SECTOR_SELECTED_REDS: '@mutations/setSectorSelectedReds',
    SET_NEWS: '@mutations/setNews',
    SET_NEWS_REDS: '@mutations/setNewsReds',
    SET_NEW: '@mutations/setNew',
    SET_STATUS: '@mutations/setStatus',
    SET_RESPONSE_MESSAGES: '@mutations/setResponseMessages',
  },
};
